### ISSUE TITLE
Logout e Login do Usuário

### ISSUE THREAD

**Issue by Fernando-S** [Fernando-S/Moodle-Trainee-Struct-Grupo-1#1]
## Páginas
Página para login
Botão para deslogar na navbar

**Comment by Fernando-S** [comment]
Para lidar com as funcionalidades de login em si, acho uma boa usar a gem devise. Ela dá um belo suporte pra isso com métodos úteis para controle do usuário atual e verificação e autenticação de login. https://launchschool.com/blog/how-to-use-devise-in-rails-for-authentication

**Comment by Lucca-h** [comment]
Boa, parece uma bela adição para o projeto.
