### ISSUE TITLE
Instalar Sorcery para o Usuário

### ISSUE THREAD

**Issue by Fernando-S** [Fernando-S/Moodle-Trainee-Struct-Grupo-1#2]

**Comment by Lucca-h** [comment]
instalei a sorcery:
adicionar sorcery à gem file 
rodar bundle install
rodar rails g sorcery:install

obs: tinham outros comandos que faziam coisas adicionais, bom checar para usar nos futuros projetos

**Comment by Lucca-h** [comment]
Commit e push devidamente dados.
A demora se explica devido à milhares de bugs miseráveis que assolaram a minha tragetória.
Falta agora modificar os campos da sorcery para deixar do jeito que queremos.
