### ISSUE TITLE
Criar Model tipo de usuário

### ISSUE THREAD

**Issue by Fernando-S** [Fernando-S/Moodle-Trainee-Struct-Grupo-1#3]

**Comment by Fernando-S** [comment]
É mesmo necessário uma model pra isso? Não podemos só adicionar um campo na Model User pra dizer o tipo (role) dele? (Aluno ou professor)

**Comment by Lucca-h** [comment]
eu lembro que nas discussões em aula, teve um debate sobre isso. Não lembro exatamente a discussão mas **acho** que podemos fazer sem, até porque parece bem mais prático. Acho que o Pedro tinha falado que isso era só pra projeto bem grande...

**Comment by Fernando-S** [comment]
Optamos por criar um campo para o tipo de usuário. Sendo assim, vou fechar essa Issue
